// Converts IBM Plex Sans SemiBold (SIL OFL 1.1) into src/engine/font.ts: glyph outlines, advances
// and kerning for the Latin set, in font units. Run after changing the font or the character set:
//   bun run scripts/build-font.ts
import { readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { join, resolve } from "node:path";
// @ts-expect-error fontkit's types aren't installed; only this script uses it
import * as fontkit from "fontkit";

const root = resolve(__dirname, "..");
const pkg = join(root, "node_modules/@fontsource/ibm-plex-sans");
const file = join(pkg, "files/ibm-plex-sans-latin-600-normal.woff");
const font = fontkit.create(readFileSync(file));

// Printable ASCII and Latin-1, plus the typographic marks people type on labels.
const wanted: string[] = [];
for (let c = 0x20; c <= 0x7e; c++) wanted.push(String.fromCharCode(c));
for (let c = 0xa0; c <= 0xff; c++) wanted.push(String.fromCharCode(c));
wanted.push(..."–—‘’“”•…€™←↑→↓");

const glyphs: Record<string, [number, string]> = {};
const p = (a: number[]) => a.map(Math.round).join(" ");
for (const ch of wanted) {
  const g = font.glyphForCodePoint(ch.codePointAt(0)!);
  if (!g || g.id === 0) continue; // .notdef: the font doesn't have it
  const d = g.path.commands.map((c: { command: string; args: number[] }) =>
    c.command === "moveTo" ? `M${p(c.args)}` : c.command === "lineTo" ? `L${p(c.args)}`
    : c.command === "quadraticCurveTo" ? `Q${p(c.args)}` : c.command === "bezierCurveTo" ? `C${p(c.args)}` : "Z").join("");
  glyphs[ch] = [g.advanceWidth, d];
}

// Kerning as the font's layout engine applies it (GPOS pair adjustments included).
const chars = Object.keys(glyphs);
const kern: Record<string, number> = {};
for (const a of chars) for (const b of chars) {
  const run = font.layout(a + b);
  if (run.glyphs.length !== 2) continue;
  const k = run.positions[0].xAdvance - run.glyphs[0].advanceWidth;
  if (k) kern[a + b] = k;
}

const out = `// Generated by scripts/build-font.ts from IBM Plex Sans SemiBold. Do not edit.
// Copyright 2019 IBM Corp. with Reserved Font Name "Plex". Licensed under the SIL Open Font
// License 1.1: see LICENSE-fonts.txt.
// Units: font units (unitsPerEm per em), +y up, baseline at 0. Each glyph: [advance, path].

export const FONT = ${JSON.stringify({ unitsPerEm: font.unitsPerEm, ascender: font.ascent, descender: font.descent, capHeight: font.capHeight })};
export const GLYPHS: Record<string, [number, string]> = ${JSON.stringify(glyphs)};
export const KERN: Record<string, number> = ${JSON.stringify(kern)};
`;
writeFileSync(join(root, "src/engine/font.ts"), out);
copyFileSync(join(pkg, "LICENSE"), join(root, "LICENSE-fonts.txt"));
console.log(`${chars.length} glyphs, ${Object.keys(kern).length} kerning pairs, ${(out.length / 1024).toFixed(0)} KB`);
